                      # <-- top-level document
restylers:            # <-- restylers key
  - prettier:
      command:
      - prettier
      - "--write"
      - "src/**/*.ts"
      arguments: []
      interpreters: []
